
// Contact Details
export const medicalConditionValues = ['Hearing', 'Learning', 'Mobility', 'Visual', 'Medical', 'other'];
export const hearAboutUsValues = ['Education Agent', 'Career & Education Expo', 'Careers Adviser', 'Print / Newspaper', 'Word of Mouth', 'Internet', 'Billboard', 'other'];

//Pass And Visa
export const visaTypes = ['Tourism', 'academic', 'Bussiness'];




export const phoneRegExp = /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/
export const str2bool = (value) => {
    if (value && typeof value === "string") {
        if (value.toLowerCase() === "true") return true;
        if (value.toLowerCase() === "false") return false;
    }
    return value;
}

export const faculties = {
    'Faculty of Electrical Engineering': ['Department of Telecommunication', 'Department of Electronics', 'Department of Systems and Control', 'Department of Power'],
    'Faculty of Computer Engineering and Science': ['Department of Software Engineering & Information', 'Department of Artificial Intelligence and Robotics', 'Department of Computer Architecture and Networks'],
    'Faculty of Mechanical Engineering and Energy':[],
    'Faculty of Architecture & Urban Engineering': ['Department of Architecture',' Department of Landscape Architecture', 'Department of Construction', 'Department of Design', 'Department of Reconstruction', 'Department of Urban Planning'],
    'Faculty of Business & Management':[' Department of Public Management', 'Department of Business Management', 'Department of Commercial Management', 'Department of Financial Management', 'Department of Industrial Management', 'Department of Entrepreneurial Management', 'Institute for Research'],
    'Faculty of Biological Sciences': ['Department of Biology', 'Department of Genetics', 'Department of Marine Biology', 'Department of Microbiology', 'Department of Plant Sciences', 'Department of Zoology'],
    'Faculty of Economics & Political Sciences': ['Department of Economics', 'Department of Political Sciences'],
    'Faculty of Energy Sciences & Modern Technologies':[ 'Department of Aeronautics', 'Department of Biotechnology', 'Department of Energy', 'Department of Nanotechnology', 'Department of Cellulose and Paper sciences'],
    'Faculty of Earth Sciences': ['Department of Geology','Department of Geography', 'Department of Geophysics'],
    'Faculty of Law': ['Department of Criminology & Criminal Law', 'Department of Intellectual Property', 'Department of International Trade Law', 'Department of Economic Law',' Department of Environmental Law', 'Department of Human Rights', 'Department of International Law', 'Department of Private Law', 'Department of Public Law'],
    'Faculty of Literature & Human Sciences': ['Department of Linguistics and Literature', 'Department of Philosophy', 'Department of History', 'Department of Archaeology', 'Department of Sociology', 'Institute of Iranology'],
    'Faculty of Mathematical Sciences': ['Department of Mathematics', 'Department of Statistics', 'Department of Computer Sciences'],
    'Faculty of Nuclear Engineering': ['Department of Applied Radiation', 'Department of Fuel-Recycling', 'Department of Radiology (Medical Radiation)'],
    'Faculty of Physical Education & Sport Sciences':[],
    'Faculty of Psychology and Education': ['Department of Psychology', 'Department of Behavioral Studies' & 'Advising, Department of Educational Sciences'],
    'Faculty of Sciences': ['Department of Chemistry', 'Department of Physics'],
    'Faculty of Civil &Water & Environmental Engineering': ['Department of Water Resources Engineering', 'Department of Water and Wastewater Engineering', 'Department of Structural and Geotechnical Engineering', 'Department of Environmental Engineering', 'Department of transportation planning'],
}

export const countryList = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];
